
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

networks:
  byfn:

services:
  explorerdb:
    image: hyperledger/explorer-db:latest
    container_name: ${EXPLORER_DB_HOSTNAME}
    hostname: ${EXPLORER_DB_HOSTNAME}
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=${EXPLORER_DB_USER}
      - DATABASE_PASSWORD=${EXPLORER_DB_PWD}
      # - TZ=${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    volumes:
      - ./explorer/app/persistence/fabric/postgreSQL/db/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ${PGDATA_FILE_PATH}:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

  explorer:
    image: hyperledger/explorer:latest
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=${EXPLORER_DB_HOSTNAME}
      - DATABASE_USERNAME=${EXPLORER_DB_USER}
      - DATABASE_PASSWD=${EXPLORER_DB_PWD}
      - DISCOVERY_AS_LOCALHOST=false
      # - TZ=${TZ}
    volumes:
      - ./explorer/net/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/net/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config/:/tmp/crypto
      - ${WALLETSTORE_FILE_PATH}:/opt/wallet
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    networks:
      - ${NETWORK_NAME}
