# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  snsrdata:
    container_name: snsrdata
    image: snsrdata
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_default 
    working_dir: /src/api-sevice/snsrdata-api
    command: ["npm", "start"]
    volumes:
      - ./api-sevice:/src/api-sevice
      - ./wallet:/src/wallet
      - ./gateway:/src/gateway
    ports:
      - 4001:4001
    networks:
      default:
        aliases:
          - example