---
apiVersion: v1
kind: Pod
metadata:
  name: util-pod
  labels:
    role: util
spec:
  serviceAccountName: OP_ACCOUNT
  restartPolicy: "Never"
  volumes:
  - name: util-pvc
    persistentVolumeClaim:
      claimName: shareclaim
  containers:
  - name: cryptogen
    image: hyperledger/fabric-tools:1.4.4
    workingDir: NFS_SHARE_PATH
    command: ["/bin/bash", "-c", "--"]
    args: ["cryptogen generate --config=NFS_SHARE_PATH/crypto-config.yaml; sleep 30"]
    volumeMounts:
     - mountPath: NFS_SHARE_PATH
       name: util-pvc
  - name: genesis
    image: hyperledger/fabric-tools:1.4.4
    workingDir: NFS_SHARE_PATH
    command: ["/bin/bash", "-c", "--"]
    args: ["sleep 30; configtxgen -profile SampleMultiNodeEtcdRaft -channelID byfn-sys-channel -outputBlock NFS_SHARE_PATH/channel-artifacts/genesis.block;"]
    env:
     - name: ORDERER_URL
       value: ORDERER_NAME:7050
     - name: ORDERER2_URL
       value: ORDERER2_NAME:8050
     - name: ORDERER3_URL
       value: ORDERER3_NAME:9050
     - name: ORDERER4_URL
       value: ORDERER4_NAME:10050
     - name: ORDERER5_URL
       value: ORDERER5_NAME:11050
     - name: FABRIC_CFG_PATH
       value: NFS_SHARE_PATH
    volumeMounts:
     - mountPath: NFS_SHARE_PATH
       name: util-pvc
  - name: channel
    image: hyperledger/fabric-tools:1.4.4
    workingDir: NFS_SHARE_PATH
    command: ["/bin/bash", "-c", "--"]
    args: ["configtxgen -profile TwoOrgsChannel -outputCreateChannelTx NFS_SHARE_PATH/channel-artifacts/CHANNEL_NAME.tx -channelID CHANNEL_NAME"]
    env:
     - name: FABRIC_CFG_PATH
       value: NFS_SHARE_PATH
    volumeMounts:
     - mountPath: NFS_SHARE_PATH
       name: util-pvc
