---
apiVersion: v1
kind: Service
metadata:
  name: scanfile-svc
  labels:
    run: scanfile
spec:
  selector:
    role: scanfile
  ports:
  - protocol: TCP
    port: 4005
    targetPort: 4005

---
apiVersion: v1
kind: Service
metadata:
  name: ezscanfile-svc
  labels:
    run: ezscanfile
spec:
  selector:
    role: ezscanfile
  ports:
  - protocol: TCP
    port: 4007
    targetPort: 4007

---
apiVersion: v1
kind: Service
metadata:
  name: traceability-svc
  labels:
    run: traceability
spec:
  selector:
    role: traceability
  ports:
  - protocol: TCP
    port: 4006
    targetPort: 4006
