---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/fabric/fabric-openshift/share
    server: 192.168.36.130

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  labels:
    name: pv0002
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/fabric/fabric-openshift/backup
    server: 192.168.36.130