---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shareclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv0001

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backupclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv0002