# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  snsrdata:
    container_name: snsrdata
    image: snsrdata
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_default 
    working_dir: /src/api-service/snsrdata-api
    # command: ["npm", "start"]
    command: ["pm2-docker", "process.yml", "--only", "snsrdata"]
    volumes:
      # - ./api-service:/src/api-service
      - ./wallet:/src/wallet
      - ./gateway:/src/gateway
      # - ./../fabric-network/network/crypto-config:/src/gateway/crypto-config
    ports:
      - 4001:4001
    networks:
      - byfn